- readme.md
Update the readme after adding a new localisable string (in relation to [this](https://github.com/yudugit/html-reader/pull/296) PR).
@yudugit/idt
> Update the localisable strings

- toolbar/toolbar.js
> Prevent phoneview button overlap when logging in to web edition on touch device

- loading/loading.js
- readme.md
@jrdh 
Updates the loading script to make use of new flags added to the API. The flags allow the script to determine if the Reader has managed to begin or finish loading prior to the branded loading script being evaluated.
> Loading script async flags

- thumbnails/thumbnails.js
Emits the decrypt pages event for [this](https://github.com/yudugit/html-reader/pull/338)
@alexandergeeyudu
> Decrypt pages when displaying the thumbnail carousel

- docs/api/events.md
- docs/public/public.md
- docs/public/statistics.md
- readme.md
@domcampbell 
Adds statistics events documentation.
> Statistics events

- drawingToolbars/drawingToolbars.js
@alexandergeeyudu 
Switch to using HammerManager for the drawing toolbar buttons
> Let HammerManager handle clicks/taps on drawing toolbar

- docs/overrides/strings.md
@tobiaspowell @peter-cox @farizbenchaoui-yudu 
Anyone who wants to sign off on this massive change?
> Added Document and Archive

- build.gradle
- toolbar/toolbarConfig.json
- toolbarPhoneview/toolbarPhoneviewConfig.json
@ruxandra-codreanu-yudu Is there any sensible way I can test this short of merging it to master and doing an HTML reader release?
(NB. This PR is to merge to dev in the first instance, rather than directly to master.)
> Fix error caused by the toolbarPhoneview directory not getting copied

- docs/api/thumbnails.md
- thumbnails/thumbnails.js
To go with the thumbnail changes in yudugit/html-reader#380.
@farizbenchaoui-yudu
> Thumbnails encryption

- build.gradle
> add assets/audio/ folder to the build task

- assets/noAccess.html
- docs/api/toolbar.md
- toolbar/toolbar.js
@ruxandra-codreanu-yudu Branding pack changes to go with https://github.com/yudugit/html-reader/pull/438.
> Phoneview drm

- rollovers/productDetailsTemplate.html
Related PRs:
- Publisher: yudugit/Publisher#2044
- HTML Reader: yudugit/html-reader#520
- iOS Reader: yudugit/ios-reader#650
@peter-cox
> Allow rollovers to display stock levels

- rollovers/productDetailsTemplate.html
@peter-cox 
[Trello](https://trello.com/c/euTLPNYM/914-allow-for-product-code-in-rollovers-and-allow-html-tags)
Requires [Html-Reader PR 528](https://github.com/yudugit/html-reader/pull/528)
> include Product Code in rollover

- toolbar/style.less
- toolbar/toolbar.html
- toolbar/toolbar.js
Point 5 of [this Trello card](https://trello.com/c/CWzqlcKA)
Corresponding HTML Reader PR: yudugit/html-reader#533
@peter-cox
> Allow main toolbar buttons to be navigable via tab key

- toolbar/toolbar.html
- toolbar/toolbar.js
Point 6 of [this Trello card](https://trello.com/c/CWzqlcKA)
Corresponding HTML Reader PR: yudugit/html-reader#534
@Ryan-Yudu
> Configure main toolbar to be picked up by screen readers

- downloadPdfCustomSelectionToolbar/downloadPdfCustomSelectionToolbar.html
- downloadPdfCustomSelectionToolbar/downloadPdfCustomSelectionToolbar.js
- downloadPdfCustomSelectionToolbar/style.less
Second part of [this Trello ticket](https://trello.com/c/wO5tWqYl/)
Adds indicators on the pdf custom selection toolbar to show when pages are selected.
HTML Reader Changes: yudugit/html-reader#547
@ruxandra-codreanu-yudu
> Add download pdf page indicators

- docs/overrides/strings.md
- placeholder.svg
Html Reader PR: yudugit/html-reader#562
@peter-cox
> Implement using SVG tiles instead of JPG ones

- _config.yml
- build.gradle
> Include the placeholder.svg file when building the branding pack

- docs/api/events.md
- docs/api/loading.md
- docs/overrides/strings.md
- loading/loading.html
- loading/loading.js
- loading/style.less
[Trello](https://trello.com/c/KbWCCJaH)
[HTML Reader changes](https://github.com/yudugit/html-reader/pull/566)
@ruxandra-codreanu-yudu
> Remove loading bar

- toolbar/style.less
- toolbarPhoneview/style.less
[Trello](https://trello.com/c/6KUkkRPy)
[HTML Reader changes](https://github.com/yudugit/html-reader/pull/572)
@ruxandra-codreanu-yudu
> Accessibility fixes

- toolbar/toolbar.js
Missed this case when adding hover text for [this ticket](https://trello.com/c/ag8lplP9)
@ruxandra-codreanu-yudu
> Add hover text to brandable buttons
